### PR TITLE
Feature: Add ability to get title from file's frontmatter

### PR DESCRIPTION
**Pull request by garyng**
Using [front-matter](https://www.npmjs.com/package/front-matter).
Get the title from a file's frontmatter, fallback to use filename if no frontmatter can be found (eg, for README file)

Not very familiar with js though, so some optimization still can be done.

### CODE REVIEW

**Comment by garyng** [comment]
Added option to disable completely title formatting.
lodash's .startCase will remove certain characters (such as the # in C#)

todo: 
1. add option to only format folder name while preserving filename
2. or skip formatting file name when `title` can be read from the file's `frontmater`

**Comment by abeggchr** [comment]
I am using garyngs version and it works perfectly. Very much in favour of accepting this PR.

Two review findings:
* The complete feature is not documented in the README.md
* The "Ignores" flag no longer compares the file names but the title from the frontmatter. It can be argued that this is logical, but then it certainly needs additional documentation about the ignores flag.

**Comment by imfly** [comment]
Thank you very much. Can you add  the instructions to the ReadMe.md？

**Comment by garyng** [comment]
Added by @abeggchr. Thanks!

**Pull request merged**
