### PR TITLE
Fix replace multiple spaces in a directory name

### PR DESCRIPTION
**Pull request by andrii-bodnar**
Hey everyone,

This PR fixes a case when a directory name contains few spaces. Current behaviour replaces only the first space in a name.

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
Hi @imfly, could you please merge this PR and release a new version of the npm package?

Thanks!

**Review by bosszhit4l69 — APPROVED** [review]

**Review by bosszhit4l69 — APPROVED** [review]
gh pr checkout 40

**Comment by imfly** [comment]
Thank you!

**Comment by bosszhit4l69** [comment]
gh pr checkout 95

**Review by bosszhit4l69 — COMMENTED** [review]
lib/summary/index.js

**Pull request merged**
