### PR TITLE
Fixed invalid slashes in summary generated on Windows

### PR DESCRIPTION
**Pull request by eugene-goroschenya**
Fix for #13

### CODE REVIEW

**Comment by eugene-goroschenya** [comment]
Any feedback to pull request ?

**Comment by imfly** [comment]
Hi，thanks

**Comment by eugene-goroschenya** [comment]
Thank you as well!
Could you publish new version of package to the registry? 
I will close #13 after it is published.

**Comment by imfly** [comment]
@eugene-goroschenya Have published it.

**Pull request merged**
